install:
	ln -s /home/hss/2_tools/fortran-duckdb/libduckdb-linux-amd64/duckdb.h /usr/lib/duckdb.h
	ln -s /home/hss/2_tools/fortran-duckdb/libduckdb-linux-amd64/duckdb.hpp /usr/lib/duckdb.hpp
	ln -s /home/hss/2_tools/fortran-duckdb/libduckdb-linux-amd64/libduckdb.so /usr/lib/libduckdb.so

uninstall:
	unlink /usr/lib/duckdb.h
	unlink /usr/lib/duckdb.hpp
	unlink /usr/lib/libduckdb.so
